#!/usr/bin/env python3
"""Convert a chase CSV into Firmware/Seesaw/chase.h.

Usage:
    python csv_to_header.py path/to/chase.csv [-o ../Seesaw/chase.h]

CSV format:
    - One row per animation frame.
    - Each row contains comma-separated R,G,B,R,G,B,... values (0..255).
    - Every row must have the same length, and length must be a multiple of 3.
    - Blank lines and lines starting with '#' are skipped.

The number of LEDs is auto-detected as (columns / 3); the number of frames
is the number of non-empty rows. Both are written into the generated header
as CHASE_NUM_LEDS and CHASE_NUM_FRAMES.

The generated header is what the firmware compiles. The Seesaw.ino sketch
plays the data forward for SIDE_A and in reverse for SIDE_B; you do NOT
need a separate file per direction.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import List, Tuple


HEADER_TEMPLATE = """\
#pragma once
#include <Arduino.h>

// =====================================================================
// CHASE DATA - generated by Firmware/tools/csv_to_header.py
// =====================================================================
//
// Source: {source}
// Frames: {num_frames}
// LEDs:   {num_leds}
//
// SIDE_A plays forward (frame 0 -> CHASE_NUM_FRAMES-1).
// SIDE_B plays reverse (CHASE_NUM_FRAMES-1 -> frame 0).
// The same frame is written to both LED strips simultaneously.
// =====================================================================

#define CHASE_NUM_LEDS    {num_leds}
#define CHASE_NUM_FRAMES  {num_frames}

const uint8_t chase[CHASE_NUM_FRAMES][CHASE_NUM_LEDS * 3] PROGMEM = {{
  // ========== BEGIN CHASE DATA ==========
{rows}
  // ==========  END CHASE DATA  ==========
}};
"""


def parse_csv(path: Path) -> Tuple[List[List[int]], int]:
    """Return (rows_of_ints, num_leds)."""
    rows: List[List[int]] = []
    with path.open("r", newline="") as f:
        reader = csv.reader(f)
        for line_no, raw in enumerate(reader, start=1):
            cells = [c.strip() for c in raw if c.strip() != ""]
            if not cells:
                continue
            if cells[0].startswith("#"):
                continue
            try:
                values = [int(c) for c in cells]
            except ValueError as e:
                raise SystemExit(f"line {line_no}: non-integer value ({e})")
            for v in values:
                if not 0 <= v <= 255:
                    raise SystemExit(
                        f"line {line_no}: value {v} out of range 0..255"
                    )
            if len(values) % 3 != 0:
                raise SystemExit(
                    f"line {line_no}: {len(values)} columns is not a multiple of 3"
                )
            rows.append(values)

    if not rows:
        raise SystemExit("CSV contains no data rows")

    width = len(rows[0])
    for i, row in enumerate(rows[1:], start=2):
        if len(row) != width:
            raise SystemExit(
                f"row {i} has {len(row)} columns, expected {width}"
            )
    return rows, width // 3


def format_row(values: List[int]) -> str:
    triplets = []
    for i in range(0, len(values), 3):
        triplets.append(
            f"{values[i]:3},{values[i + 1]:3},{values[i + 2]:3}"
        )
    return "  { " + ",  ".join(triplets) + " }"


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("input", type=Path, help="Input CSV file")
    p.add_argument(
        "-o", "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "Seesaw" / "chase.h",
        help="Output header path (default: ../Seesaw/chase.h)",
    )
    args = p.parse_args()

    if not args.input.exists():
        print(f"Input file not found: {args.input}", file=sys.stderr)
        return 2

    rows, num_leds = parse_csv(args.input)
    formatted = ",\n".join(format_row(r) for r in rows)
    output = HEADER_TEMPLATE.format(
        source=args.input.name,
        num_frames=len(rows),
        num_leds=num_leds,
        rows=formatted,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    print(
        f"Wrote {args.output} ({len(rows)} frames x {num_leds} LEDs, "
        f"{len(rows) * num_leds * 3} bytes of PROGMEM)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
