#!/usr/bin/env python3
"""Convert an animation CSV into Firmware/Seesaw/chase.h or idle.h.

Usage:
    # Play-mode chase (default; writes ../Seesaw/chase.h):
    python csv_to_header.py path/to/chase.csv

    # Idle-mode animation (writes ../Seesaw/idle.h):
    python csv_to_header.py path/to/idle.csv --target idle

    # Custom output path (overrides the default for the chosen target):
    python csv_to_header.py path/to/chase.csv -o ../Seesaw/chase.h

CSV format (same for both targets):
    - One row per animation frame.
    - Each row contains comma-separated R,G,B,R,G,B,... values (0..255).
    - Every row must have the same length, and length must be a multiple of 3.
    - Blank lines and lines starting with '#' are skipped.

The number of LEDs is auto-detected as (columns / 3); the number of frames
is the number of non-empty rows. Both are written into the generated header
as <PREFIX>_NUM_LEDS and <PREFIX>_NUM_FRAMES, where <PREFIX> is CHASE for
the play target and IDLE for the idle target.

The generated header is what the firmware compiles. The Seesaw.ino sketch
plays the play chase forward on the SIDE_A pair when SIDE_A bottoms out and
in reverse on the SIDE_B pair when SIDE_B bottoms out (only the triggered
side lights up). The idle animation loops continuously on all four strips
when no tilt event has fired in IDLE_TIMEOUT_MS, with a per-strip frame
offset (see config.h) so the four strips animate phase-shifted.
<PREFIX>_NUM_LEDS must be <= STRIP_NUM_LEDS in config.h for either target.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import List, Tuple


TARGETS = {
    "play": {
        "default_output": "chase.h",
        "title": "CHASE DATA",
        "data_marker": "CHASE",
        "const_leds": "CHASE_NUM_LEDS",
        "const_frames": "CHASE_NUM_FRAMES",
        "array": "chase",
        "description": (
            "// SIDE_A pair plays forward (frame 0 -> CHASE_NUM_FRAMES-1) when\n"
            "// SIDE_A bottoms out; SIDE_B pair plays reverse\n"
            "// (CHASE_NUM_FRAMES-1 -> frame 0) when SIDE_B bottoms out. Only\n"
            "// one pair lights at a time; the strips on the non-triggered\n"
            "// side stay dark. The two pins in the active pair receive\n"
            "// identical data so they animate in lock-step.\n"
            "// CHASE_NUM_LEDS must be <= STRIP_NUM_LEDS in config.h."
        ),
    },
    "idle": {
        "default_output": "idle.h",
        "title": "IDLE CHASE DATA",
        "data_marker": "IDLE",
        "const_leds": "IDLE_NUM_LEDS",
        "const_frames": "IDLE_NUM_FRAMES",
        "array": "idle",
        "description": (
            "// Played continuously on all four LED strips when the seesaw\n"
            "// is idle (no tilt events for IDLE_TIMEOUT_MS, default 60s).\n"
            "// Each strip plays the same animation but shifted by\n"
            "// IDLE_FRAME_OFFSET_<strip> frames (see config.h), creating a\n"
            "// phase-shifted wave across the four strips. The animation\n"
            "// loops as long as the seesaw stays idle; the first tilt\n"
            "// event drops it and switches into PLAY mode.\n"
            "// IDLE_NUM_LEDS must be <= STRIP_NUM_LEDS in config.h."
        ),
    },
}


HEADER_TEMPLATE = """\
#pragma once
#include <Arduino.h>

// =====================================================================
// {title} - generated by Firmware/tools/csv_to_header.py
// =====================================================================
//
// Source: {source}
// Frames: {num_frames}
// LEDs:   {num_leds}
//
{description}
// =====================================================================

#define {const_leds}    {num_leds}
#define {const_frames}  {num_frames}

const uint8_t {array}[{const_frames}][{const_leds} * 3] PROGMEM = {{
  // ========== BEGIN {data_marker} DATA ==========
{rows}
  // ==========  END {data_marker} DATA  ==========
}};
"""


def parse_csv(path: Path) -> Tuple[List[List[int]], int]:
    """Return (rows_of_ints, num_leds)."""
    rows: List[List[int]] = []
    with path.open("r", newline="") as f:
        reader = csv.reader(f)
        for line_no, raw in enumerate(reader, start=1):
            cells = [c.strip() for c in raw if c.strip() != ""]
            if not cells:
                continue
            if cells[0].startswith("#"):
                continue
            try:
                values = [int(c) for c in cells]
            except ValueError as e:
                raise SystemExit(f"line {line_no}: non-integer value ({e})")
            for v in values:
                if not 0 <= v <= 255:
                    raise SystemExit(
                        f"line {line_no}: value {v} out of range 0..255"
                    )
            if len(values) % 3 != 0:
                raise SystemExit(
                    f"line {line_no}: {len(values)} columns is not a multiple of 3"
                )
            rows.append(values)

    if not rows:
        raise SystemExit("CSV contains no data rows")

    width = len(rows[0])
    for i, row in enumerate(rows[1:], start=2):
        if len(row) != width:
            raise SystemExit(
                f"row {i} has {len(row)} columns, expected {width}"
            )
    return rows, width // 3


def format_row(values: List[int]) -> str:
    triplets = []
    for i in range(0, len(values), 3):
        triplets.append(
            f"{values[i]:3},{values[i + 1]:3},{values[i + 2]:3}"
        )
    return "  { " + ",  ".join(triplets) + " }"


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("input", type=Path, help="Input CSV file")
    p.add_argument(
        "--target",
        choices=sorted(TARGETS.keys()),
        default="play",
        help="Which animation to generate: 'play' writes chase.h, "
             "'idle' writes idle.h. Default: play.",
    )
    p.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output header path. Default depends on --target: "
             "../Seesaw/chase.h (play) or ../Seesaw/idle.h (idle).",
    )
    args = p.parse_args()

    target = TARGETS[args.target]

    if args.output is None:
        args.output = (
            Path(__file__).resolve().parent.parent
            / "Seesaw"
            / target["default_output"]
        )

    if not args.input.exists():
        print(f"Input file not found: {args.input}", file=sys.stderr)
        return 2

    rows, num_leds = parse_csv(args.input)
    formatted = ",\n".join(format_row(r) for r in rows)
    output = HEADER_TEMPLATE.format(
        title=target["title"],
        data_marker=target["data_marker"],
        const_leds=target["const_leds"],
        const_frames=target["const_frames"],
        array=target["array"],
        description=target["description"],
        source=args.input.name,
        num_frames=len(rows),
        num_leds=num_leds,
        rows=formatted,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    print(
        f"Wrote {args.output} [{args.target}] "
        f"({len(rows)} frames x {num_leds} LEDs, "
        f"{len(rows) * num_leds * 3} bytes of PROGMEM)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
